# Generated by Django 3.0 on 2020-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('c_name', models.CharField(choices=[('web design', 'Web Design'), ('sales & marketing', 'Sales & Marketing'), ('software', 'Software'), ('php', 'PHP'), ('networking', 'Networking')], max_length=50)),
                ('j_type', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('work at home', 'Work from Home')], max_length=20)),
                ('mobile_n', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('india', 'India'), ('canada', 'Canada'), ('uk', 'UK'), ('australia', 'Australia')], max_length=50)),
                ('resume', models.FileField(default='xyz.pdf', upload_to='resume/')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
