# Generated by Django 3.0 on 2020-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('ctype', models.CharField(choices=[('pvt.', 'Pvt. Ltd.'), ('limited', 'Limited'), ('ltd.', 'Ltd.'), ('proprietor', 'Proprietor')], max_length=15)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govid', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('vid', 'Voter ID Card'), ('passport', 'Passport'), ('dl', 'Driving Licence')], max_length=8)),
                ('upid', models.ImageField(default='b.jpg', upload_to='ID/')),
            ],
            options={
                'db_table': 'Id',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('domestic', 'Domestic'), ('village', 'Village')], max_length=15)),
                ('area', models.CharField(choices=[('it', 'IT'), ('sales & marketing', 'Sales & marketing'), ('accounting', 'Accounting'), ('data entry', 'Data Entry')], max_length=20)),
                ('eneed', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54)])),
                ('work', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('accountant', 'Accountant'), ('sales & management', 'Sales & Management'), ('e-commerce', 'E-commerce')], max_length=20)),
            ],
            options={
                'db_table': 'Information',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Business',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
