# Generated by Django 3.0 on 2020-02-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='emailid',
            field=models.CharField(max_length=100),
        ),
    ]
