# Generated by Django 3.0 on 2020-02-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_auto_20200204_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='emailid',
            new_name='email',
        ),
    ]
