# Generated by Django 3.0 on 2020-02-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_auto_20200204_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
